### ISSUE TITLE
Anybody knows better GUI library for swift?

### ISSUE THREAD

**Issue by ardawan** [TomasLinhart/SwiftGtk#10]
Seems TomasLinhart the author of SwiftGtk, doesn't care about people's problem. so if anybody else knows better GUI library for Swift please let me know. 
Thanks

**Comment by seunlanlege** [comment]
you can always write your own swift bindings for gtk

**Comment by lf-araujo** [comment]
@ardawan  the most advanced binding is in https://github.com/rhx/SwiftGtk

**Comment by ardawan** [comment]
@lf-araujo thanks for sharing. I'll give a try. hope to find some good documentation

**Comment by TomasLinhart** [comment]
I am sorry for not answering issues. I resolved all issues and it should be possible to use the project on Linux and macOS now.

But it is an experimental Gtk+ binding so you will struggle if you will want to write a full app with that but feel free to try what is out there and you can contribute if you want. I hope I will be able to answer and assist more now. I finally got a grasp on GitHub notifications! 😉 

Also having a quick look at [rhx/SwiftGtk](https://github.com/rhx/SwiftGtk), it looks it covers more because it generates all bindings so I guess you will have more luck with that.
