### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by darkfrog26** [TomasLinhart/SwiftGtk#2]
I am trying to use your library on Ubuntu 15.10 and I get the following output when I attempt to build my project:

```
Cloning https://github.com/TomasLinhart/SwiftGtk
git clone --recursive --depth 10 https://github.com/TomasLinhart/SwiftGtk /media/sf_projects/prototype/hello-swift/Hello/Packages/SwiftGtk

Segmentation fault (core dumped)
```

**Comment by HopperMCS** [comment]
Any code? Next Friday I can triage for bugs as well. I'm interested in contributing because obviously this dude's bindings work. The reason I ask is because your code could be an issue. Also, make sure you have the right version of Gtk installed because Gtk+3 tends to not stay the same all time between releases for some reason. However, if you used the example code from the README, there may be a problem. I'm gonna fork this repo because nothing's been committed in five months, and why re-write what someone else started all over again.

**Comment by TomasLinhart** [comment]
Please try with latest Swift and latest SwiftGtk and if the problem still persists feel free to reopen the issue.
